# Generated by Django 3.2.13 on 2023-08-01 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('brand_name', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('fitting_type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xl')], max_length=50)),
                ('is_imported', models.BooleanField(default=False)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.category')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('price', models.FloatField(blank=True, null=True)),
                ('select_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.item')),
            ],
            bases=('app.basemodel',),
        ),
    ]
